CREATE TABLE [dbo].[Blog]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[Title] NVARCHAR(200) NOT NULL,
	[Slug] NVARCHAR(255) NOT NULL UNIQUE,
	[Summary] NVARCHAR(500) NULL,
	[BodyContent] NVARCHAR(MAX) NULL,
	[DateCreated] DATETIME NULL,
	PRIMARY KEY CLUSTERED (Id ASC) 
)
