/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/
MERGE INTO Blog AS Target
USING (VALUES
	(1,'All the Tourist Stuff You Should Probably Do in Oslo','all-the-tourist-stuff-you-should-probably-do-in-oslo','The special spots travellers need to see in Norway’s capital.','Surrounded by forests and lakes, ringed by hills and embraced by waters of Oslo fjord, the capital of Norway is a true gem. It will not impress you with cosmopolitan busyness, with rush and loudness of large metropolises. Instead, you will be astonished by the gentle rhythm of this city, by the harmony of wild nature and architectural innovation.','2017-06-02 12:00:00.000'),
	(2,'Behind the Scenes of the Old Carlsberg Factory','behind-the-scenes-of-the-old-carlsberg-factory','Go even MORE behind the scenes of a behind the scenes tour.','The history of Carlsberg beer, founded in 1847, is interwoven with the history of Denmark. A can of Carlsberg pilsner is the symbol of the every day – simple and traditional, and available everywhere from 7-11 to restaurants.','2017-02-20 11:00:00.000'),
	(3, 'How to Spot the Northern Lights in Iceland', 'how-to-spot-the-northern-lights-in-iceland', 'With this natural phenomenon, there are no guarantees. ', 'I first heard about the northern lights when reading someone else’s bucket list as a kid. I didn’t know what they were but decided that they must belong on my bucket list, along with such gems as “bake a soufflé” and “take the midnight train going anywhere”. The northern lights, also known as aurora borealis, are among the great natural wonders of the world; a staple on many travellers’ wish lists.', '2016-06-15 15:00:00.000'), 
	(4, 'Scandi Six: Norwegian Instagram Accounts to Follow', 'scandi-six-norwegian-instagram-accounts-to-follow', 'Get a glimpse of life in Norway, including landscapes, food, design and fashion, with these photographs.', 'Oh, Norway, you pretty thing. There’s so much to see in this small, quiet country with the unbelievable landscape. But there’s also more to Norway than fjords; design, fashion, interiors and foods are all worth exploring.', '2017-02-24 17:30:00.000'), 
	(5, 'All the Tourist Stuff You Should Probably do in Stockholm', 'all-the-tourist-stuff-you-should-probably-do-in-stockholm', 'A local’s guide to the attractions, museums and places to visit in the Swedish capital.', 'Let’s talk about all the tourist stuff you should probably do in Stockholm…or, at least, some of it Truth be told, wherever you go in Stockholm, there’s always something that makes you sigh in wonder and pull out your camera. If you are a tourist (or want to feel like one for a day), looking to journey through the Swedish capital but feel a tad overwhelmed, let our little guide get you started. You’ll be sure to discover much more along the way (we can’t wait to hear all about it! ', '2017-01-11 14:00:00.000'), 
	(6, 'Call for Creatives: We’re Going to Oslo!', 'call-for-creatives-were-going-to-oslo', 'If you’re Norway-based and want to work with us, get in touch!', 'If you’re a photographer, writer or creative who is living in, or has previously lived in, Norway – particularly Oslo – we want to work with you! We’re open to submissions and are always on the look-out for an interesting angle, article or event.', '2016-12-27 08:00:00.000'), 
	(7, 'Scandi in... Berlin', 'scandi-in-berlin', 'Where to eat, drink and stay when you want Scandi style in Berlin, Germany.', 'Berlin’s confidence and restless energy is intoxicating. It’s an unpretentious city that doesn’t care what people think of it; it doesn’t settle and it never plays it safe. A place for the adventurous and the thrill-seeker; David Bowie said it best when he called Berlin "the greatest cultural extravaganza that one could imagine."', '2017-04-25 11:00:00.000'), 
	(8, 'Scandi in... Riga', 'scandi-in-riga', 'A Scandiphile’s guide to Latvia’s charming capital.', 'Riga, capital of Latvia, has all the charm you’d expect in an eastern European city: a maze of tram lines weaving their way through winding streets, a stunning old town at its centre, hip neighbourhoods that have that urban je-ne-sais-quoi, sporadically punctuated by brutalist Soviet architecture.', '2017-03-01 19:00:00.000'), 
	(9, 'Heading Northside: Two Women, Two Bikes, Two Lunchboxes', 'heading-northside-two-women-two-bikes-two-lunchboxes', 'On cycling from Copenhagen to Aarhus on a whim, with the promise of good music hanging ahead like a carrot.', 'After months of darkness spent marinating in a selection of Netto’s finest cabernet sauvignon my first inkling of summer comes when music festivals release their line-ups. Each ticket becomes a ray of hope – a reminder that soon the cab sav will be swapped for boxed rosé, guzzled down in a tent of questionable structural integrity as you gear up for yet another day of sweat, grime and musical bliss.', '2017-05-05 15:00:00.000'), 
	(10, 'Get in On the Party: G&T Weekends', 'get-in-on-the-party-gt-weekends', 'Want to attend a traditional Swedish crayfish party? How about seeing the Northern Lights in Iceland?', 'There’s nothing better than a weekend away with your friend or partner. Except for a weekend away when you don’t have to do any planning. I mean, nothing. Food? Three meals a day prepared by the best local chefs. Drinks? Flowing freely. Itinerary? Scheduled for you, based on the most interesting cultural activities available in the destination. Are you seriously not sold on this yet?', '2017-04-11 10:00:00.000'), 
	(11, 'Scandi Six: Where to Rent a Bicycle in Copenhagen', 'scandi-six-where-to-rent-a-bicycle-in-copenhagen', 'Whether you’re visiting the city or just need an bike for a few days, here are the places to get the best deals and quality.', 'If you’re visiting Copenhagen and want to live like a local, you’ll want to rent a bicycle to get around town. It’s not only a fairly inexpensive way to travel, it’s also one of the best ways to experience the city.', '2017-03-03 09:00:00.000'), 
	(12, 'Scandi Six: Secret Hot Springs of Iceland', 'scandi-six-secret-hot-springs-of-iceland', 'The spots you’ll want to know about on your next adventure.', 'Known as the land of fire and ice, Iceland is, in geological terms, a young country. It also lies on the divergent boundary between two tectonic plates – the Eurasian and the North American – directly above a hotspot known as the Iceland plume.', '2017-03-13 20:00:00.000'), 
	(13, 'Hail in April & Other Stories: Weather in Denmark, Month-by-Month', 'hail-in-april-other-stories-weather-in-denmark-month-by-month', 'So you know when to travel to Denmark and what to wear.', 'Oh boy. Weather in Denmark. We are getting into political territory. There’s nothing Danes like to talk about more than the weather. It’s a national pastime and who could blame them? The weather here has more twists and turns than a Raymond Chandler novel (or, Fast & Furious: Tokyo Drift. Pick your reference). One of the things you’ll hear most often in Denmark is “there’s no such thing as bad weather, only bad clothes,” which is a dirty lie obviously. It’s a fair point though: in Denmark, you need to be sartorially prepared.', '2017-02-10 13:00:00.000'), 
    (14, 'Treat Yourself: Kurhotel Skodsborg & The Restaurant by Kroun', 'treat-yourself-kurhotel-skodsborg-the-restaurant-by-kroun', 'Enjoy a luxurious day, weekend or holiday in Denmark with a top spa and restaurant experience.', 'Denmark is not the least expensive place to treat yourself to a day – or even an hour – of luxury. So why not maximize the experience when you can? Kurhotel Skodsborg right on the west coast of Sjælland is easily accessible on the train and hosts a beautiful hotel facility as well as an extensive fitness centre, spa, rooftop terrace, brasserie and the gourmet Restaurant by Kroun.', '2017-01-20 18:00:00.000')
)
AS Source(Id,Title,Slug,Summary,BodyContent,DateCreated)
ON Target.Id = Source.Id
WHEN NOT MATCHED BY TARGET THEN
INSERT (Title,Slug,Summary,BodyContent,DateCreated)
VALUES (Title,Slug,Summary,BodyContent,DateCreated);